/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LedgeKanban {
        "bins": string;
    }
}
declare global {
    interface HTMLLedgeKanbanElement extends Components.LedgeKanban, HTMLStencilElement {
    }
    var HTMLLedgeKanbanElement: {
        prototype: HTMLLedgeKanbanElement;
        new (): HTMLLedgeKanbanElement;
    };
    interface HTMLElementTagNameMap {
        "ledge-kanban": HTMLLedgeKanbanElement;
    }
}
declare namespace LocalJSX {
    interface LedgeKanban {
        "bins"?: string;
    }
    interface IntrinsicElements {
        "ledge-kanban": LedgeKanban;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ledge-kanban": LocalJSX.LedgeKanban & JSXBase.HTMLAttributes<HTMLLedgeKanbanElement>;
        }
    }
}
